<a href="https://colab.research.google.com/github/DarylUnix/ML-Study/blob/main/school-study1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DEPRESSION DATASET DESCRIPTION**
We all know now a days mental health is one of the major problem among the students in the current days, So the dataset of some students is provided such that anyone can make health detection system that the student has any such type of depression or not. Depression.csv is basically the training file and the test.csv is for the testing the model with true labels.

Kaggle Link: https://www.kaggle.com/datasets/indubarnwal/depression-dataset

# **DATA PREPARATION**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, classification_report

from google.colab import drive
drive.mount("/content/drive/", force_remount=True)
df = pd.read_csv("/content/drive/MyDrive/Dataset/Depression.csv", low_memory=False)
df

Mounted at /content/drive/


Family Problem        Ignored Social Support  Age  Gender Demographics  \
0                 No  Sleep quality           High   38    Male        Rural   
1                 No  Sleep quality           High   51    Male        Urban   
2                Yes       Exercise       Moderate   32  Female        Urban   
3                 No       Exercise           High   64  Female        Rural   
4                Yes  Sleep quality            Low   31    Male        Rural   
...              ...            ...            ...  ...     ...          ...   
29994             No  Sleep quality            Low   45    Male        Urban   
29995             No       Exercise            Low   35  Female        Urban   
29996             No  Sleep quality       Moderate   19  Female        Urban   
29997             No           Diet            Low   59  Female        Urban   
29998            Yes  Sleep quality       Moderate   27  Female        Rural   

           CGPA Financial Problem  Depression  
0      Moderate              Mild           0  
1          High              Mild           0  
2          High       Significant           0  
3      Moderate          Moderate           0  
4      Moderate          Moderate           0  
...         ...               ...         ...  
29994       Low              Mild           0  
29995  Moderate          Moderate           0  
29996      High       Significant           0  
29997  Moderate              Mild           0  
29998       Low       Significant           0  

[29999 rows x 9 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Family Problem     29999 non-null  object
 1   Ignored            29999 non-null  object
 2   Social Support     29999 non-null  object
 3   Age                29999 non-null  int64 
 4   Gender             29999 non-null  object
 5   Demographics       29999 non-null  object
 6   CGPA               29999 non-null  object
 7   Financial Problem  29999 non-null  object
 8   Depression         29999 non-null  int64 
dtypes: int64(2), object(7)
memory usage: 2.1+ MB


# **DATA CLEANING**

In [ ]:
check = df.isnull().sum()
print("Missing values found? F/N: ", check.all())

Missing values found? F/N:  False


In [ ]:
df['T_Ignored'] = df['Ignored'].replace({'Sleep quality': 0,'Diet': 1, 'Exercise': 2})
df['T_Gender'] = df['Gender'].replace({'Male': 0, 'Female': 1})
df['T_Demographics'] = df['Demographics'].replace({'Rural': 0, 'Urban': 1})
df['T_Family_Problem'] = df['Family Problem'].replace({'No': 0, 'Yes': 1})
df['T_Social_Support'] = df['Social Support'].replace({'Low': 0, 'Moderate': 1, 'High':2})
df['T_CGPA'] = df['CGPA'].replace({'Moderate': 1, 'Low': 0, 'High': 2})
df['T_Financial_Problem'] = df['Financial Problem'].replace({'Mild': 0, 'Moderate': 1, 'Significant':2})
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Family Problem       29999 non-null  object
 1   Ignored              29999 non-null  object
 2   Social Support       29999 non-null  object
 3   Age                  29999 non-null  int64 
 4   Gender               29999 non-null  object
 5   Demographics         29999 non-null  object
 6   CGPA                 29999 non-null  object
 7   Financial Problem    29999 non-null  object
 8   Depression           29999 non-null  int64 
 9   T_Ignored            29999 non-null  int64 
 10  T_Gender             29999 non-null  int64 
 11  T_Demographics       29999 non-null  int64 
 12  T_Family_Problem     29999 non-null  int64 
 13  T_Social_Support     29999 non-null  int64 
 14  T_CGPA               29999 non-null  int64 
 15  T_Financial_Problem  29999 non-null  int64 
dtypes: i

In [ ]:
df.drop('Gender', axis=1, inplace=True)
df.drop('Ignored', axis=1, inplace=True)
df.drop('Family Problem', axis=1, inplace=True)
df.drop('Demographics', axis=1, inplace=True)
df.drop('Social Support', axis=1, inplace=True)
df.drop('CGPA', axis=1, inplace=True)
df.drop('Financial Problem', axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  29999 non-null  int64
 1   Depression           29999 non-null  int64
 2   T_Ignored            29999 non-null  int64
 3   T_Gender             29999 non-null  int64
 4   T_Demographics       29999 non-null  int64
 5   T_Family_Problem     29999 non-null  int64
 6   T_Social_Support     29999 non-null  int64
 7   T_CGPA               29999 non-null  int64
 8   T_Financial_Problem  29999 non-null  int64
dtypes: int64(9)
memory usage: 2.1 MB


# **SPLITTING**

In [ ]:
x = df.drop('Depression', axis=1)
x

Age  T_Ignored  T_Gender  T_Demographics  T_Family_Problem  \
0       38          0         0               0                 0   
1       51          0         0               1                 0   
2       32          2         1               1                 1   
3       64          2         1               0                 0   
4       31          0         0               0                 1   
...    ...        ...       ...             ...               ...   
29994   45          0         0               1                 0   
29995   35          2         1               1                 0   
29996   19          0         1               1                 0   
29997   59          1         1               1                 0   
29998   27          0         1               0                 1   

       T_Social_Support  T_CGPA  T_Financial_Problem  
0                     2       1                    0  
1                     2       2                    0  
2                     1       2                    2  
3                     2       1                    1  
4                     0       1                    1  
...                 ...     ...                  ...  
29994                 0       0                    0  
29995                 0       1                    1  
29996                 1       2                    2  
29997                 0       1                    0  
29998                 1       0                    2  

[29999 rows x 8 columns]

In [ ]:
y = df['Depression']
y.values

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
x_train, x_test, y_train, y_test=train_test_split (x,y,test_size=0.2)

In [ ]:
x_train

Age  T_Ignored  T_Gender  T_Demographics  T_Family_Problem  \
21421   32          1         0               1                 0   
1070    46          2         0               0                 0   
21328   35          2         1               0                 0   
21295   63          0         1               1                 1   
9421    38          2         0               1                 1   
...    ...        ...       ...             ...               ...   
8985    47          2         0               0                 1   
28681   55          1         1               0                 0   
4404    22          2         1               0                 1   
8269    30          1         0               0                 1   
25932   56          0         0               0                 1   

       T_Social_Support  T_CGPA  T_Financial_Problem  
21421                 1       2                    2  
1070                  0       2                    1  
21328                 2       0                    0  
21295                 0       1                    2  
9421                  1       1                    1  
...                 ...     ...                  ...  
8985                  1       1                    1  
28681                 2       2                    1  
4404                  2       1                    0  
8269                  2       0                    1  
25932                 1       2                    2  

[23999 rows x 8 columns]

In [ ]:
x_test

Age  T_Ignored  T_Gender  T_Demographics  T_Family_Problem  \
27105   46          0         1               1                 1   
25191   22          0         1               0                 1   
5094    51          2         0               1                 0   
17652   58          0         1               1                 0   
1008    35          0         0               1                 0   
...    ...        ...       ...             ...               ...   
14511   59          0         1               1                 1   
2171    23          0         1               0                 1   
12909   50          0         0               1                 0   
5623    42          0         1               1                 0   
6811    19          1         1               0                 1   

       T_Social_Support  T_CGPA  T_Financial_Problem  
27105                 1       1                    1  
25191                 1       2                    0  
5094                  0       2                    2  
17652                 0       2                    1  
1008                  0       2                    2  
...                 ...     ...                  ...  
14511                 0       0                    2  
2171                  1       0                    2  
12909                 1       1                    0  
5623                  1       2                    1  
6811                  1       1                    0  

[6000 rows x 8 columns]

In [ ]:
y_train.values

array([0, 0, 0, ..., 0, 0, 1])

# **BUILD MODEL**

In [ ]:
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [ ]:
predicted_value=model.predict(x_test)
predicted_value

array([1, 1, 0, ..., 1, 1, 0])

In [ ]:
tp=0
tn=0
fn=0
fp=0

featured_value = np.array(x_test.values)
real = np.array(y_test.values)
predicted = np.array(predicted_value)
age = np.array(['Age'])

for i in range (y_test.size):
  if  predicted[i] == real[i]:
    classifier = "True Positive"
    tp=tp+1
  if  predicted[i] == real[i]==0:
    classifier = "True Negative"
    tn=tn+1
  if  predicted[i]==0 and real[i]==1:
    classifier = "False Positive"
    fp=fp+1
  if  predicted[i]==1 and real[i]==0:
    classifier = "False Negative"
    fn=fn+1

print("True Positive (TP): ", tp)
print("True Negative (TN): ", tn)
print("False Positive (FP): ", fp)
print("False Negative (FN): ", fn)

True Positive (TP):  4266
True Negative (TN):  3979
False Positive (FP):  0
False Negative (FN):  1734


# **CONFUSION MATRIX**

In [ ]:
cm = confusion_matrix(predicted_value, y_test)
cm

array([[3979,    0],
       [1734,  287]])

In [ ]:
accuracy_score(predicted_value, y_test)*100

71.1

# **TEST CASE**

In [ ]:
NOC = int(input('Please Input Number of cases: '))
for x in range(1, NOC + 1):
    print(f"Case {x}\n")

    df_sample = pd.DataFrame(columns=['Age','T_Ignored','T_Gender','T_Demographics','T_Family_Problem', 'T_Social_Support', 'T_CGPA', 'T_Financial_Problem'])
    while True:
      g_answer = input('Input your Gender (Male/Female): ')
      if g_answer == "Male":
        T_Gender = 0
        break
      elif g_answer == "Female":
        T_Gender = 1
        break
      else:
        print("Input is wrong! Please try again")
    while True:
      d_answer = input('Input your Area Demographic (Rural/Urban): ')
      if d_answer == "Rural":
        T_Demographics = 0
        break
      elif d_answer == "Urban":
        T_Demographics = 1
        break
      else:
        print("Input is wrong! Please try again")
    while True:
      F_ans = input('Are you currently experiencing family problems? (Yes/No): ')
      if F_ans == "No":
        T_Family_Problem = 0
        break
      elif F_ans == "Yes":
        T_Family_Problem = 1
        break
      else:
        print("Input is wrong! Please try again")
    while True:
      a_ans = input('Enter your Age (18-65): ')
      if int(a_ans) >= 18 and int(a_ans) <= 65:
        Age = a_ans
        break
      else:
        print("Input is not in Age Range! Please try again")
    while True:
      i_ans = input('Which of these factors have you been ignoring lately (Sleep/Diet/Exercise): ')
      if i_ans == "Sleep":
        T_Ignored = 0
        break
      elif i_ans == "Diet":
        T_Ignored = 1
        break
      elif i_ans == "Exercise":
        T_Ignored = 2
        break
      else:
        print("Input is wrong! Please try again")
    while True:
      ss_ans = input('Do you receive any form of social support from friends, peers, or family? (Low/Moderate/High): ')
      if ss_ans == "Low":
        T_Social_Support = 0
        break
      elif ss_ans == "Moderate":
        T_Social_Support = 1
        break
      elif ss_ans == "High":
        T_Social_Support = 2
        break
      else:
        print("Input is wrong! Please try again")
    while True:
      c_ans = input ('What is your CGPA level? (Low/Average/High): ')
      if c_ans == "Low":
        T_CGPA = 0
        break
      elif c_ans == "Average":
        T_CGPA = 1
        break
      elif c_ans == "High":
        T_CGPA = 2
        break
      else:
        print("Input is wrong! Please try again")
    while True:
      fp_ans = input('Are you currently experiencing any financial problems? (Mild/Average/Significant): ')
      if fp_ans == "Mild":
        T_Financial_Problem = 0
        break
      elif fp_ans == "Average":
        T_Financial_Problem = 1
        break
      elif fp_ans == "Significant":
        T_Financial_Problem = 2
        break
      else:
        print("Input is wrong! Please try again")

    df_sample.loc[len(df_sample.index)]=[Age,T_Ignored,T_Gender,T_Demographics,T_Family_Problem,T_Social_Support,T_CGPA,T_Financial_Problem]

    pred = model.predict(df_sample)
    if pred == 1:
      print("\nIt is possible that you are currently experiencing symptoms of depression. It's important to seek professional help if you can. Here are some additional recommendations to consider:\n"
          "1. **Seek Professional Help**: Consult with a mental health professional such as a therapist or counselor.\n"
          "2. **Support Groups**: Consider joining a support group where you can share experiences and receive support.\n"
          "3. **Healthy Lifestyle**: Maintain a balanced diet and engage in regular physical activity.\n"
          "4. **Avoid Substances**: Steer clear of alcohol and drugs, as they can exacerbate symptoms.\n"
          "5. **Relaxation Techniques**: Practice relaxation techniques such as meditation, deep breathing exercises, or yoga.\n"
          "6. **Social Support**: Reach out to trusted friends or family members for support and connection.\n")
    else:
      print("\nYou are not currently showing signs of depression. Continue to maintain a healthy lifestyle. Here are some tips to stay well:\n"
          "1. **Stay Active**: Engage in regular exercise to boost your mood and energy levels.\n"
          "2. **Balanced Diet**: Eat a balanced and nutritious diet to support your overall well-being.\n"
          "3. **Stay Connected**: Keep in touch with friends and family to maintain strong social connections.\n"
          "4. **Relaxation Techniques**: Incorporate relaxation practices such as meditation or yoga into your routine.\n"
          "5. **Seek Help if Needed**: If you ever feel overwhelmed, don't hesitate to seek professional help.\n")

Please Input Number of cases: 1
Case 1

Input your Gender (Male/Female): Male
Input your Area Demographic (Rural/Urban): Urban
Are you currently experiencing family problems? (Yes/No): Yes
Enter your Age (18-65): 33
Which of these factors have you been ignoring lately (Sleep/Diet/Exercise): Diet
Do you receive any form of social support from friends, peers, or family? (Low/Moderate/High): High
What is your CGPA level? (Low/Average/High): High
Are you currently experiencing any financial problems? (Mild/Average/Significant): Mild

You are not currently showing signs of depression. Continue to maintain a healthy lifestyle. Here are some tips to stay well:
1. **Stay Active**: Engage in regular exercise to boost your mood and energy levels.
2. **Balanced Diet**: Eat a balanced and nutritious diet to support your overall well-being.
3. **Stay Connected**: Keep in touch with friends and family to maintain strong social connections.
4. **Relaxation Techniques**: Incorporate relaxation practic

# **Data for testing**

In [ ]:
test = pd.read_csv("/content/drive/MyDrive/Dataset/test.csv", low_memory=False)
test.sample(10)

Family Problem        Ignored Social Support  Age  Gender Demographics  \
17235            Yes       Exercise       Moderate   60    Male        Rural   
13311             No       Exercise       Moderate   24  Female        Rural   
8680              No           Diet       Moderate   64    Male        Urban   
13660            Yes  Sleep quality            Low   45  Female        Urban   
5689             Yes  Sleep quality       Moderate   51    Male        Rural   
13973             No           Diet       Moderate   21    Male        Rural   
19271             No  Sleep quality       Moderate   25  Female        Urban   
2151             Yes           Diet           High   32  Female        Rural   
15193             No           Diet            Low   28  Female        Rural   
8480              No           Diet           High   60    Male        Urban   

           CGPA Financial Problem  Depression  
17235       Low       Significant           0  
13311      High          Moderate           0  
8680   Moderate          Moderate           0  
13660       Low          Moderate           0  
5689   Moderate              Mild           0  
13973  Moderate              Mild           0  
19271  Moderate              Mild           0  
2151   Moderate          Moderate           0  
15193       Low       Significant           0  
8480   Moderate       Significant           0